### ISSUE TITLE
Media Player

### ISSUE THREAD

**Issue by tarek99samy** [MohmedMonsef/Marioplex-Android#1]
The **Music Player at bottom** doesn't play/pause tracks , it is just allow to tab next/previous.

**Comment by hagerali99** [comment]
i tried this case multiple times from several phones and the track plays/pauses. maybe the problem was in the internet connection

**Comment by tarek99samy** [comment]
No Internet connection problem was found , according to latest push, i have found the same problem.

For more explanation:
1. login and after that don't click on anything
2. the **bottom media player** (which is a small bar that if you clicked on the image it will open the full screen media player) , have a **heart** button and right beside it have a **play/pause** button, click on this **play/pause** button many consecutive times it will be freezes.

**Comment by hagerali99** [comment]
the bug is solved the problem was that the user was allowed to click on the pause/play button even if the track wasn't loaded yet.
