### ISSUE TITLE
Edit Playlist Name

### ISSUE THREAD

**Issue by tarek99samy** [MohmedMonsef/Marioplex-Android#10]
The form in which you edit existing playlist name need **Submit** button

**Comment by hagerali99** [comment]
when you press done on the soft keypad the request is submitted

**Comment by tarek99samy** [comment]
I think the submit button must exist regardless of the keypad of the mobile. this is the case like the form of creating playlist and you solved that case.

**Comment by hagerali99** [comment]
i solved it because i didn't notice it existed in spotify but I added a submit button now to the edit playlist form.
