### ISSUE TITLE
Any Album Preview

### ISSUE THREAD

**Issue by tarek99samy** [MohmedMonsef/Marioplex-Android#6]
When go to the **preview** which has the songs of the playlist and  play a song inside playlist, then go back, then try to enter this **preview** again, it doesn't respond anymore.

**Comment by hagerali99** [comment]
i tried this case multiple tomes from several phones and i can't find the problem maybe it's just the internet connection.

**Comment by tarek99samy** [comment]
According to latest push to the **dev** branch, this case still happens. 
For more explanation :
1. open any playlist, for example **Just the beginning**
2. click on **and more**
3. play any track
4. go back and try to enter again.

**Comment by hagerali99** [comment]
just the beginning is an album not a playlist when i tried your case i tried it on a playlist not an album so there wasn't any problem but now i found the bug and fixed it.
